language: r
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel

after_success:
  - test $TRAVIS_R_VERSION = "3.2.4" && Rscript -e 'devtools::install_github("jimhester/covr")' -e 'covr::codecov()'
